version: '3'
services:
  conduit:
    restart: always
    env_file: .env
    build: .
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    networks:
      - web_network
    command: python main.py /app/example/user_script.py

  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - conduit

networks:
  web_network:
    driver: bridge
